### PR TITLE
Extra features

### LINKED ISSUE #3: Add concurrent sorting
Would be a great feature since it is very sort bound currently. Otherwise works well! 👍

### PR DESCRIPTION
**Pull request by yonderblue**
- Key/val support
- Parallel sorting
- Duplicate removal
- Size fetching

I expect this PR to be contentious but opening in case you are interested, plus missing tests/benches.
Another thing I would probably add is some buf pooling since there are a lot of allocations showing in the profiler.

fixes #3

### CODE REVIEW

**Comment by dim** [comment]
@yonderblue first of all: thanks, contributions are much appreciated. You have addressed quite a few things that need a bit of dissecting:

1. the reason why I chose a simple `[]byte` over a key/value interface is the fact that you can create your own on top of `[]byte`, just encode your key and your value into a byte slice e.g. as `KEYLEN + KEY + VALUE` then just use a custom `Less` function which only takes into account they key part. I am happy to include convenience wrappers on top of the existing API (instead of changing the low-level implementation) in a separate PR
2. parallel sorting is interesting, but do you have any benchmarks to back it up? I know that the `sort` package has been gradually improved over time by the core team while `twotwotwo/sorts` is unmaintained for over five years.
3. duplicate removal is a great idea! Would you mind extracting it into a separate PR (maybe with tests, I can help with that though)?
4. I am not sure what `Size` tells you but happy to expose it.
5. for buffer pooling, please see https://github.com/bsm/extsort/pull/5 ;)

**Comment by dim** [comment]
Here's what I had in mind regarding point 1:

```go
package mypackage

import (
	"bytes"
	"encoding/binary"
)

type KV []byte

// TODO: choose your preferred key/val types
// TODO: add pooling to suit your use case
func NewKV(key string, val []byte) KV {
	kn := len(key)
	vn := len(val)
	kv := make([]byte, binary.MaxVarintLen32+kn+vn)
	nn := binary.PutUvarint(kv, uint64(len(key)))
	copy(kv[nn:], key)
	copy(kv[nn+kn:], val)
	return KV(kv[:nn+kn+vn])
}

func (kv KV) KeyBytes() []byte {
  key, _ := kv.Split()
  return key
}

func (kv KV) Split() ([]byte, []byte) {
	raw := kv.Raw()
	u, n := binary.Uvarint(raw)
	o := n + int(u)
	return raw[n:o], raw[o:]
}

func KVLess(a, b []byte) bool {
	return bytes.Compare(KV(a).KeyBytes(), KV(b).KeyBytes()) < 0
}
```

**Comment by yonderblue** [comment]
> 1. the reason why I chose a simple `[]byte` over a key/value interface is the fact that you can create your own on top of `[]byte`, just encode your key and your value into a byte slice e.g. as `KEYLEN + KEY + VALUE` then just use a custom `Less` function which only takes into account they key part. I am happy to include convenience wrappers on top of the existing API (instead of changing the low-level implementation) in a separate PR

That is what I started with, however it doesn't perform well even when using a simple ReadUvarint to get only the key part in the Less function. Having support for the kv separation allows a much faster straight bytes.Compare. Also the existing Less function doesn't support an error return.
An alternative could be to provide an Item interface that is accepted in Sorter.Append that has a Less function and a ToBytes/FromBytes. However I like the simplicity of kv since it is such a common case and a user can still do extra encoding in the val if they wish. That might be solvable with some wrappers too though.

> 2. parallel sorting is interesting, but do you have any benchmarks to back it up? I know that the `sort` package has been gradually improved over time by the core team while `twotwotwo/sorts` is unmaintained for over five years.

Sorry my benchmarks are at the moment up a level in my application and it is certainly faster, but I can see about adding a quick one in some downtime. The pkg choice is somewhat random as there are lots of these out there. I did benchmark the radix sort in that same pkg though and it was slower than std sort pkg.

> 3. duplicate removal is a great idea! Would you mind extracting it into a separate PR (maybe with tests, I can help with that though)?

Sure, it might be a little bit though so feel free.

> 4. I am not sure what `Size` tells you but happy to expose it.

In my application I have to continually write some data up until some limit, then consume the Sorter and start again. Also somewhat related a Reset could be useful and perhaps waste a little less than a Close/New. Note when I use the compression the size here is more important since it would reflect compressed size, however using the compression was much slower for me.

> 5. for buffer pooling, please see #5 ;)

Nice! Thanks for that, also I'm curious why the pkg choice over sync.Pool?

**Comment by dim** [comment]
Ad 1: I will take another look. I can see the appeal and I am not a fan of an `Item` interface. Let me think about it ...
Ad 2: I could make this optional, something like `Options.Sort func(sort.Interface)`. The default `sort.Sort` should be sufficient for most users and I prefer not to add another dependency. At the same time, this would allow you to customise the behaviour in your app. Would you mind submitting a PR just for that?
Ad 3: See #6 
Ad 4: Same, would you mind submitting a separate PR just for that?
Ad 5: Despite my preference for stdapi packages, `bytebufferpool` is battle-tested and has some nice features under the hood - https://github.com/valyala/bytebufferpool/blob/v1.0.0/pool.go#L81. Plus, it takes care of all the pitfalls of https://staticcheck.io/docs/checks#SA6002

**Comment by dim** [comment]
@yonderblue see #7

**Comment by dim** [comment]
.. aaaaand #8

**Comment by dim** [comment]
Right, only `Size` is still missing and I would appreciate a PR for that :)

**Comment by yonderblue** [comment]
Thanks! https://github.com/bsm/extsort/pull/9

**Pull request closed without merging**
