### PR TITLE
Keep last item when deduplicating

### PR DESCRIPTION
**Pull request by yonderblue**
Make it deterministic that the last added item is kept on duplicate values.
When using extsort as part of a db like system, usually the last item (updates) is most important.

### CODE REVIEW

**Comment by dim** [comment]
Thanks, but shouldn't this be configurable somehow?

**Comment by yonderblue** [comment]
> Thanks, but shouldn't this be configurable somehow?

I think this would be the vast majority of cases, and it wasn't configurable before. As long as it is documented I'd say wait for someone to want it the other way.

**Comment by dim** [comment]
Well, it was documented in the example. Changing it would break backwards compatibility and would require a major version change. Just trying to see if there's a less obtrusive way

**Comment by yonderblue** [comment]
> Well, it was documented in the example. 

I wouldn't consider that contract documentation.

Also the existing ordering wasn't deterministic anyways (which is why I added the extra section bit etc), so someone should not have been relying on it.

**Pull request merged**
